import Relico.Correctness.GlobalMultiStorePayloadActorDispatchCorrespondence

set_option autoImplicit false

#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorDispatchCorrespondence.actorPriorityDispatchStep_forward_of_targetBase
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorDispatchCorrespondence.actorOrderDispatchStep_backward_of_sourceBase
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorDispatchCorrespondence.synchronizedActorPriorityDispatch_forward
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorDispatchCorrespondence.synchronizedActorPriorityDispatch_backward
