import Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution

set_option autoImplicit false

#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.ActorDispatchFrame
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.SourceActorDispatchEvent
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.TargetActorDispatchEvent
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.ActorDispatchEventCorresponds
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.ActorDispatchEventTraceCorresponds
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.SourceActorPriorityDispatchSteps
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.TargetActorOrderDispatchSteps
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.sourceActorPriorityDispatchSteps_single
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.targetActorOrderDispatchSteps_single
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.sourceActorPriorityDispatchSteps_forward
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.targetActorOrderDispatchSteps_backward
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorFiniteExecution.actorDispatchEventTraceCorresponds_length_eq
