import Relico.Correctness.GlobalMultiStorePayloadActorObservableProjection

set_option autoImplicit false

#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorObservableProjection.actorDispatchFrameTrace
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorObservableProjection.sourceActorDispatchObservableTrace
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorObservableProjection.targetActorDispatchObservableTrace
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorObservableProjection.actorDispatchObservableTrace_eq
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorObservableProjection.sourceActorPriorityDispatchSteps_actorTrace
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorObservableProjection.targetActorOrderDispatchSteps_actorTrace
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorObservableProjection.sourceActorPriorityDispatchObservable_forward
#check _root_.Relico.Correctness.GlobalMultiStorePayloadActorObservableProjection.targetActorOrderDispatchObservable_backward
