import Relico.Correctness.MultiStorePayloadDetailedStartupCompletion

set_option autoImplicit false

#check Relico.DTR.MultiStorePayloadState.StartupBodyComplete
#check Relico.DTR.DetailedMultiStorePayloadState.StartupBodyComplete

#check Relico.LF.MultiStorePayloadState.StartupBodyComplete
#check Relico.LF.DetailedMultiStorePayloadState.StartupBodyComplete

#check Relico.Correctness.multiStorePayloadStartupBody_compile_eq_nil_iff
#check Relico.Correctness.multiStorePayloadRuntimeStartupBodyComplete_iff
#check Relico.Correctness.multiStorePayloadDetailedStableStartupBodyComplete_iff

#check Relico.Correctness.multiStorePayloadSourceStartupBodyComplete_of_targetStable
#check Relico.Correctness.multiStorePayloadTargetStartupBodyComplete_of_sourceStable_targetStable

#check Relico.Correctness.multiStorePayloadStartupFinite_forward_completion_when_target_stable
#check Relico.Correctness.multiStorePayloadStartupFinite_backward_completion

#check Relico.Correctness.multiStorePayloadStartupObservable_forward_completion_when_target_stable
#check Relico.Correctness.multiStorePayloadStartupObservable_backward_completion

#print axioms Relico.Correctness.multiStorePayloadStartupBody_compile_eq_nil_iff
#print axioms Relico.Correctness.multiStorePayloadRuntimeStartupBodyComplete_iff
#print axioms Relico.Correctness.multiStorePayloadDetailedStableStartupBodyComplete_iff

#print axioms Relico.Correctness.multiStorePayloadSourceStartupBodyComplete_of_targetStable
#print axioms Relico.Correctness.multiStorePayloadTargetStartupBodyComplete_of_sourceStable_targetStable

#print axioms Relico.Correctness.multiStorePayloadStartupFinite_forward_completion_when_target_stable
#print axioms Relico.Correctness.multiStorePayloadStartupFinite_backward_completion

#print axioms Relico.Correctness.multiStorePayloadStartupObservable_forward_completion_when_target_stable
#print axioms Relico.Correctness.multiStorePayloadStartupObservable_backward_completion
